export type InvestmentOutlookDirection =
  | "Very Bullish"
  | "Bullish"
  | "Neutral"
  | "Bearish"
  | "Very Bearish"
  | "Unknown";

export type CollectorDemand =
  | "Exceptional"
  | "Strong"
  | "Moderate"
  | "Weak"
  | "Unknown";

export type SupplyOutlook =
  | "Highly Constrained"
  | "Constrained"
  | "Balanced"
  | "Abundant"
  | "Unknown";

export type MarketMaturity =
  | "Emerging"
  | "Growing"
  | "Established"
  | "Mature"
  | "Unknown";

export type InvestmentOutlookConfidence =
  | "High"
  | "Medium"
  | "Low"
  | "Insufficient";

export type InvestmentOutlookInput = {
  currentPrice: number | null;
  fairValue: number | null;

  /**
   * Expected score ranges: 0–100.
   */
  marketRatingScore: number;
  trendScore: number;
  riskScore: number;
  marketHealthScore: number;
  investmentGradeScore: number;

  /**
   * Expected return generated by the Price Target Engine.
   */
  expectedReturnPercent: number | null;

  /**
   * Market participation inputs.
   */
  recentSalesCount: number;
  activeListingsCount: number;

  /**
   * Shared Market Confidence generated by confidence.ts.
   */
  marketConfidenceScore: number;
  marketConfidence: InvestmentOutlookConfidence;

  /**
   * Current market context.
   */
  change30d: number | null;
};

export type InvestmentOutlookResult = {
  overallOutlook: InvestmentOutlookDirection;
  overallScore: number;

  shortTermOutlook: InvestmentOutlookDirection;
  shortTermScore: number;

  longTermOutlook: InvestmentOutlookDirection;
  longTermScore: number;

  collectorDemand: CollectorDemand;
  collectorDemandScore: number;

  supplyOutlook: SupplyOutlook;
  supplyScore: number;

  marketMaturity: MarketMaturity;
  maturityScore: number;

  confidence: InvestmentOutlookConfidence;
  confidenceScore: number;

  summary: string;
  strengths: string[];
  headwinds: string[];
};

function clamp(
  value: number,
  minimum = 0,
  maximum = 100,
): number {
  return Math.min(
    Math.max(value, minimum),
    maximum,
  );
}

function roundScore(value: number): number {
  return Math.round(clamp(value));
}

function getOutlook(
  score: number,
): InvestmentOutlookDirection {
  if (score >= 80) {
    return "Very Bullish";
  }

  if (score >= 65) {
    return "Bullish";
  }

  if (score >= 45) {
    return "Neutral";
  }

  if (score >= 30) {
    return "Bearish";
  }

  return "Very Bearish";
}

function getCollectorDemand(
  score: number,
): CollectorDemand {
  if (score >= 82) {
    return "Exceptional";
  }

  if (score >= 65) {
    return "Strong";
  }

  if (score >= 45) {
    return "Moderate";
  }

  return "Weak";
}

function getSupplyOutlook(
  score: number,
): SupplyOutlook {
  if (score >= 80) {
    return "Highly Constrained";
  }

  if (score >= 62) {
    return "Constrained";
  }

  if (score >= 40) {
    return "Balanced";
  }

  return "Abundant";
}

function getMarketMaturity(
  score: number,
): MarketMaturity {
  if (score >= 80) {
    return "Mature";
  }

  if (score >= 62) {
    return "Established";
  }

  if (score >= 40) {
    return "Growing";
  }

  return "Emerging";
}

function getExpectedReturnScore(
  expectedReturnPercent: number | null,
): number {
  if (expectedReturnPercent === null) {
    return 50;
  }

  if (expectedReturnPercent >= 25) {
    return 95;
  }

  if (expectedReturnPercent >= 15) {
    return 85;
  }

  if (expectedReturnPercent >= 8) {
    return 72;
  }

  if (expectedReturnPercent >= 0) {
    return 58;
  }

  if (expectedReturnPercent >= -10) {
    return 38;
  }

  return 20;
}

function buildSummary({
  overallOutlook,
  shortTermOutlook,
  longTermOutlook,
  collectorDemand,
  supplyOutlook,
  expectedReturnPercent,
  currentPrice,
  fairValue,
}: {
  overallOutlook: InvestmentOutlookDirection;
  shortTermOutlook: InvestmentOutlookDirection;
  longTermOutlook: InvestmentOutlookDirection;
  collectorDemand: CollectorDemand;
  supplyOutlook: SupplyOutlook;
  expectedReturnPercent: number | null;
  currentPrice: number;
  fairValue: number;
}): string {
  const sentences: string[] = [];

  sentences.push(
    `The overall investment outlook is ${overallOutlook.toLowerCase()}, with a ${shortTermOutlook.toLowerCase()} short-term view and a ${longTermOutlook.toLowerCase()} long-term outlook.`,
  );

  if (
    collectorDemand === "Exceptional" ||
    collectorDemand === "Strong"
  ) {
    sentences.push(
      `${collectorDemand} collector demand supports continued market interest.`,
    );
  } else {
    sentences.push(
      `${collectorDemand} collector demand provides limited support for future appreciation.`,
    );
  }

  if (
    supplyOutlook === "Highly Constrained" ||
    supplyOutlook === "Constrained"
  ) {
    sentences.push(
      `${supplyOutlook} supply conditions may support long-term pricing.`,
    );
  } else if (supplyOutlook === "Abundant") {
    sentences.push(
      "Abundant active supply may limit near-term price growth.",
    );
  }

  if (currentPrice > fairValue) {
    sentences.push(
      "The current market price remains above estimated fair value, which may limit near-term returns.",
    );
  } else {
    sentences.push(
      "The current market price remains at or below estimated fair value.",
    );
  }

  if (
    expectedReturnPercent !== null &&
    expectedReturnPercent >= 8
  ) {
    sentences.push(
      "The current price target indicates meaningful appreciation potential.",
    );
  } else if (
    expectedReturnPercent !== null &&
    expectedReturnPercent < 0
  ) {
    sentences.push(
      "The current price target indicates limited immediate upside.",
    );
  }

  return sentences.join(" ");
}

export function calculateInvestmentOutlook(
  input: InvestmentOutlookInput,
): InvestmentOutlookResult {
  /*
   * Investment Outlook consumes Shared Market Confidence.
   *
   * It does not independently calculate or classify
   * confidence from another analytics engine.
   */
  const confidenceScore = roundScore(
    input.marketConfidenceScore,
  );

  const confidence =
    input.marketConfidence;

  if (
    input.currentPrice === null ||
    input.fairValue === null ||
    input.currentPrice <= 0 ||
    input.fairValue <= 0 ||
    confidence === "Insufficient"
  ) {
    return {
      overallOutlook: "Unknown",
      overallScore: 0,

      shortTermOutlook: "Unknown",
      shortTermScore: 0,

      longTermOutlook: "Unknown",
      longTermScore: 0,

      collectorDemand: "Unknown",
      collectorDemandScore: 0,

      supplyOutlook: "Unknown",
      supplyScore: 0,

      marketMaturity: "Unknown",
      maturityScore: 0,

      confidence: "Insufficient",
      confidenceScore,

      summary:
        "Additional market data is required before TCGMVP can produce a dependable investment outlook.",

      strengths: [],

      headwinds: [
        "Insufficient market evidence limits long-term analysis.",
      ],
    };
  }

  const marketRatingScore = clamp(
    input.marketRatingScore,
  );

  const trendScore = clamp(
    input.trendScore,
  );

  const riskScore = clamp(
    input.riskScore,
  );

  const marketHealthScore = clamp(
    input.marketHealthScore,
  );

  const investmentGradeScore = clamp(
    input.investmentGradeScore,
  );

  const expectedReturnScore =
    getExpectedReturnScore(
      input.expectedReturnPercent,
    );

  /*
   * Short-term outlook emphasizes:
   *
   * Trend: 40%
   * Expected return: 30%
   * Market health: 20%
   * Inverse risk: 10%
   */
  const shortTermScore = roundScore(
    trendScore * 0.4 +
      expectedReturnScore * 0.3 +
      marketHealthScore * 0.2 +
      (100 - riskScore) * 0.1,
  );

  /*
   * Collector demand uses market participation,
   * trend quality, and underlying investment quality.
   */
  const collectorDemandScore = roundScore(
    investmentGradeScore * 0.4 +
      marketRatingScore * 0.3 +
      trendScore * 0.2 +
      marketHealthScore * 0.1,
  );

  /*
   * Higher scores represent tighter supply.
   *
   * Strong sales relative to listings indicate that
   * available inventory is being absorbed.
   */
  const salesToListingsRatio =
    input.activeListingsCount > 0
      ? input.recentSalesCount /
        input.activeListingsCount
      : input.recentSalesCount > 0
        ? 2
        : 0;

  const supplyScore = roundScore(
    clamp(
      45 +
        salesToListingsRatio * 20 +
        (marketHealthScore - 50) * 0.25,
      0,
      100,
    ),
  );

  /*
   * Market maturity is based on evidence depth,
   * liquidity, and market health.
   *
   * Shared Market Confidence contributes to maturity,
   * but maturity remains a separate market attribute.
   */
  const maturityScore = roundScore(
    confidenceScore * 0.45 +
      marketHealthScore * 0.3 +
      clamp(input.recentSalesCount * 4) * 0.15 +
      clamp(input.activeListingsCount * 3) * 0.1,
  );

  /*
   * Long-term outlook emphasizes investment quality,
   * collector demand, market rating, and constrained supply.
   */
  const longTermScore = roundScore(
    investmentGradeScore * 0.3 +
      collectorDemandScore * 0.25 +
      marketRatingScore * 0.2 +
      supplyScore * 0.15 +
      (100 - riskScore) * 0.1,
  );

  /*
   * Overall investment outlook:
   *
   * Market Rating: 35%
   * Price Target / Expected Return: 20%
   * Investment Grade: 20%
   * Trend: 15%
   * Inverse Risk: 10%
   */
  let overallScore = roundScore(
    marketRatingScore * 0.35 +
      expectedReturnScore * 0.2 +
      investmentGradeScore * 0.2 +
      trendScore * 0.15 +
      (100 - riskScore) * 0.1,
  );

  /*
   * Reduce extreme conclusions when confidence is lower.
   *
   * Scores are pulled toward neutral rather than simply
   * reduced. This keeps forward-looking conclusions
   * conservative when market evidence is limited.
   */
  const confidenceMultiplier =
    confidence === "High"
      ? 1
      : confidence === "Medium"
        ? 0.8
        : 0.55;

  overallScore = roundScore(
    50 +
      (overallScore - 50) *
        confidenceMultiplier,
  );

  const shortTermOutlook =
    getOutlook(shortTermScore);

  const longTermOutlook =
    getOutlook(longTermScore);

  const overallOutlook =
    getOutlook(overallScore);

  const collectorDemand =
    getCollectorDemand(
      collectorDemandScore,
    );

  const supplyOutlook =
    getSupplyOutlook(supplyScore);

  const marketMaturity =
    getMarketMaturity(maturityScore);

  const strengths: string[] = [];
  const headwinds: string[] = [];

  if (trendScore >= 65) {
    strengths.push(
      "Positive market momentum supports the near-term outlook.",
    );
  } else if (trendScore <= 35) {
    headwinds.push(
      "Weak price momentum creates near-term pressure.",
    );
  }

  if (investmentGradeScore >= 65) {
    strengths.push(
      "Strong underlying investment quality supports the long-term thesis.",
    );
  } else if (
    investmentGradeScore <= 35
  ) {
    headwinds.push(
      "Weak investment fundamentals limit long-term conviction.",
    );
  }

  if (marketHealthScore >= 65) {
    strengths.push(
      "Healthy liquidity and stable pricing support market confidence.",
    );
  } else if (
    marketHealthScore <= 35
  ) {
    headwinds.push(
      "Weak market health reduces confidence in future performance.",
    );
  }

  if (riskScore <= 35) {
    strengths.push(
      "Lower overall risk supports a more dependable outlook.",
    );
  } else if (riskScore >= 65) {
    headwinds.push(
      "Elevated risk may produce greater price instability.",
    );
  }

  if (supplyScore >= 65) {
    strengths.push(
      "Constrained supply may support long-term price appreciation.",
    );
  } else if (supplyScore <= 35) {
    headwinds.push(
      "Abundant available supply may limit appreciation.",
    );
  }

  if (
    input.expectedReturnPercent !== null &&
    input.expectedReturnPercent >= 8
  ) {
    strengths.push(
      "The current price target indicates meaningful potential return.",
    );
  } else if (
    input.expectedReturnPercent !== null &&
    input.expectedReturnPercent < 0
  ) {
    headwinds.push(
      "The current price target indicates limited near-term upside.",
    );
  }

  if (
    input.currentPrice >
    input.fairValue
  ) {
    headwinds.push(
      "The current market price is above estimated fair value.",
    );
  } else if (
    input.currentPrice <
    input.fairValue * 0.9
  ) {
    strengths.push(
      "The current market price provides a meaningful valuation cushion.",
    );
  }

  if (confidence === "Low") {
    headwinds.push(
      "Limited market evidence reduces outlook confidence.",
    );
  }

  const summary = buildSummary({
    overallOutlook,
    shortTermOutlook,
    longTermOutlook,
    collectorDemand,
    supplyOutlook,

    expectedReturnPercent:
      input.expectedReturnPercent,

    currentPrice:
      input.currentPrice,

    fairValue:
      input.fairValue,
  });

  return {
    overallOutlook,
    overallScore,

    shortTermOutlook,
    shortTermScore,

    longTermOutlook,
    longTermScore,

    collectorDemand,
    collectorDemandScore,

    supplyOutlook,
    supplyScore,

    marketMaturity,
    maturityScore,

    confidence,
    confidenceScore,

    summary,

    strengths:
      strengths.slice(0, 5),

    headwinds:
      headwinds.slice(0, 5),
  };
}