export type InvestmentOutlookDirection =
  | "Very Bullish"
  | "Bullish"
  | "Neutral"
  | "Bearish"
  | "Very Bearish"
  | "Unknown";

export type CollectorDemand =
  | "Exceptional"
  | "Strong"
  | "Moderate"
  | "Weak"
  | "Unknown";

export type SupplyOutlook =
  | "Highly Constrained"
  | "Constrained"
  | "Balanced"
  | "Abundant"
  | "Unknown";

export type MarketMaturity =
  | "Emerging"
  | "Growing"
  | "Established"
  | "Mature"
  | "Unknown";

export type InvestmentOutlookConfidence =
  | "High"
  | "Medium"
  | "Low"
  | "Insufficient";

export type InvestmentOutlookInput = {
  /*
   * Broader market/reference price.
   *
   * Useful for market context, but not assumed
   * to represent an executable purchase price.
   */
  referencePrice: number | null;

  /*
   * Lowest eligible actionable listing.
   *
   * This represents the price at which an
   * investor could realistically enter today.
   */
  entryPrice: number | null;

  fairValue: number | null;

  /**
   * Expected score ranges: 0–100.
   */
  marketRatingScore: number;
  trendScore: number;
  riskScore: number;
  marketHealthScore: number;

  /**
   * Expected return generated by Price Target.
   *
   * This should already be calculated from
   * actionable Entry Price rather than the
   * broader reference price.
   */
  expectedReturnPercent: number | null;

  /**
   * Market participation.
   */
  recentSalesCount: number;
  activeListingsCount: number;

  /**
   * Shared Market Confidence.
   */
  marketConfidenceScore: number;
  marketConfidence: InvestmentOutlookConfidence;

  /**
   * Current market context.
   */
  change30d: number | null;
};

export type InvestmentOutlookResult = {
  overallOutlook: InvestmentOutlookDirection;
  overallScore: number;

  shortTermOutlook: InvestmentOutlookDirection;
  shortTermScore: number;

  longTermOutlook: InvestmentOutlookDirection;
  longTermScore: number;

  collectorDemand: CollectorDemand;
  collectorDemandScore: number;

  supplyOutlook: SupplyOutlook;
  supplyScore: number;

  marketMaturity: MarketMaturity;
  maturityScore: number;

  confidence: InvestmentOutlookConfidence;
  confidenceScore: number;

  summary: string;
  strengths: string[];
  headwinds: string[];
};


function clamp(
  value: number,
  minimum = 0,
  maximum = 100
): number {
  return Math.min(
    Math.max(value, minimum),
    maximum
  );
}


function roundScore(
  value: number
): number {
  return Math.round(
    clamp(value)
  );
}


function getOutlook(
  score: number
): InvestmentOutlookDirection {
  if (score >= 80) {
    return "Very Bullish";
  }

  if (score >= 65) {
    return "Bullish";
  }

  if (score >= 45) {
    return "Neutral";
  }

  if (score >= 30) {
    return "Bearish";
  }

  return "Very Bearish";
}


function getCollectorDemand(
  score: number
): CollectorDemand {
  if (score >= 82) {
    return "Exceptional";
  }

  if (score >= 65) {
    return "Strong";
  }

  if (score >= 45) {
    return "Moderate";
  }

  return "Weak";
}


function getSupplyOutlook(
  score: number
): SupplyOutlook {
  if (score >= 80) {
    return "Highly Constrained";
  }

  if (score >= 62) {
    return "Constrained";
  }

  if (score >= 40) {
    return "Balanced";
  }

  return "Abundant";
}


function getMarketMaturity(
  score: number
): MarketMaturity {
  if (score >= 80) {
    return "Mature";
  }

  if (score >= 62) {
    return "Established";
  }

  if (score >= 40) {
    return "Growing";
  }

  return "Emerging";
}


function getExpectedReturnScore(
  expectedReturnPercent: number | null
): number {
  if (expectedReturnPercent === null) {
    return 50;
  }

  if (expectedReturnPercent >= 25) {
    return 95;
  }

  if (expectedReturnPercent >= 15) {
    return 85;
  }

  if (expectedReturnPercent >= 8) {
    return 72;
  }

  if (expectedReturnPercent >= 0) {
    return 58;
  }

  if (expectedReturnPercent >= -10) {
    return 38;
  }

  return 20;
}


/*
 * Demand is derived from observable market
 * participation rather than downstream
 * composite analytics.
 *
 * Sales activity is primary.
 * Sell-through provides secondary confirmation.
 */
function calculateCollectorDemandScore(
  recentSalesCount: number,
  activeListingsCount: number
): number {
  const safeSales =
    Math.max(
      0,
      recentSalesCount
    );

  const safeListings =
    Math.max(
      0,
      activeListingsCount
    );


  let salesActivityScore: number;

  if (safeSales >= 30) {
    salesActivityScore = 100;
  } else if (safeSales >= 20) {
    salesActivityScore = 90;
  } else if (safeSales >= 10) {
    salesActivityScore = 75;
  } else if (safeSales >= 5) {
    salesActivityScore = 55;
  } else if (safeSales >= 2) {
    salesActivityScore = 35;
  } else if (safeSales === 1) {
    salesActivityScore = 20;
  } else {
    salesActivityScore = 0;
  }


  let sellThroughScore: number;

  if (
    safeListings === 0
  ) {
    sellThroughScore =
      safeSales > 0
        ? 85
        : 0;
  } else {
    const ratio =
      safeSales /
      safeListings;

    if (ratio >= 2) {
      sellThroughScore = 100;
    } else if (ratio >= 1.25) {
      sellThroughScore = 85;
    } else if (ratio >= 0.75) {
      sellThroughScore = 70;
    } else if (ratio >= 0.4) {
      sellThroughScore = 50;
    } else if (ratio >= 0.2) {
      sellThroughScore = 30;
    } else {
      sellThroughScore = 15;
    }
  }


  return roundScore(
    salesActivityScore * 0.7 +
    sellThroughScore * 0.3
  );
}


/*
 * Higher supply score means tighter supply.
 *
 * This is based on inventory absorption,
 * not investment-quality scores.
 */
function calculateSupplyScore(
  recentSalesCount: number,
  activeListingsCount: number
): number {
  const safeSales =
    Math.max(
      0,
      recentSalesCount
    );

  const safeListings =
    Math.max(
      0,
      activeListingsCount
    );


  if (
    safeSales === 0 &&
    safeListings === 0
  ) {
    return 0;
  }


  if (
    safeListings === 0
  ) {
    return safeSales > 0
      ? 90
      : 0;
  }


  if (
    safeSales === 0
  ) {
    return 15;
  }


  const ratio =
    safeSales /
    safeListings;


  if (ratio >= 2) {
    return 95;
  }

  if (ratio >= 1.25) {
    return 82;
  }

  if (ratio >= 0.75) {
    return 68;
  }

  if (ratio >= 0.4) {
    return 52;
  }

  if (ratio >= 0.2) {
    return 35;
  }

  return 20;
}


function buildSummary({
  overallOutlook,
  shortTermOutlook,
  longTermOutlook,
  collectorDemand,
  supplyOutlook,
  expectedReturnPercent,
  entryPrice,
  fairValue,
}: {
  overallOutlook:
    InvestmentOutlookDirection;

  shortTermOutlook:
    InvestmentOutlookDirection;

  longTermOutlook:
    InvestmentOutlookDirection;

  collectorDemand:
    CollectorDemand;

  supplyOutlook:
    SupplyOutlook;

  expectedReturnPercent:
    number | null;

  entryPrice:
    number | null;

  fairValue:
    number;
}): string {
  const sentences: string[] = [];


  sentences.push(
    `The overall investment outlook is ${overallOutlook.toLowerCase()}, with a ${shortTermOutlook.toLowerCase()} short-term view and a ${longTermOutlook.toLowerCase()} long-term outlook.`
  );


  if (
    collectorDemand ===
      "Exceptional" ||
    collectorDemand ===
      "Strong"
  ) {
    sentences.push(
      `${collectorDemand} observed market demand supports continued buyer interest.`
    );
  } else {
    sentences.push(
      `${collectorDemand} observed market demand provides limited support for appreciation.`
    );
  }


  if (
    supplyOutlook ===
      "Highly Constrained" ||
    supplyOutlook ===
      "Constrained"
  ) {
    sentences.push(
      `${supplyOutlook} supply conditions may support longer-term pricing.`
    );
  } else if (
    supplyOutlook ===
      "Abundant"
  ) {
    sentences.push(
      "Abundant active supply may limit near-term price growth."
    );
  }


  /*
   * Valuation language must use the actionable
   * entry price rather than the broader
   * reference-price series.
   */
  if (
    entryPrice !== null &&
    entryPrice > 0
  ) {
    if (
      entryPrice >
      fairValue * 1.03
    ) {
      sentences.push(
        "The best available entry price is above estimated fair value, which may limit near-term returns."
      );
    } else if (
      entryPrice <
      fairValue * 0.97
    ) {
      sentences.push(
        "The best available entry price is below estimated fair value, providing a modest valuation cushion."
      );
    } else {
      sentences.push(
        "The best available entry price is currently near estimated fair value."
      );
    }
  } else {
    sentences.push(
      "An actionable entry price is currently unavailable, limiting entry-value analysis."
    );
  }


  if (
    expectedReturnPercent !== null &&
    expectedReturnPercent >= 8
  ) {
    sentences.push(
      "The current price target indicates meaningful appreciation potential from the best available entry price."
    );
  } else if (
    expectedReturnPercent !== null &&
    expectedReturnPercent >= 0
  ) {
    sentences.push(
      "The current price target indicates limited but positive appreciation potential from the best available entry price."
    );
  } else if (
    expectedReturnPercent !== null
  ) {
    sentences.push(
      "The current price target indicates limited immediate upside from the best available entry price."
    );
  }


  return sentences.join(
    " "
  );
}


export function calculateInvestmentOutlook(
  input: InvestmentOutlookInput
): InvestmentOutlookResult {
  const confidenceScore =
    roundScore(
      input.marketConfidenceScore
    );

  const confidence =
    input.marketConfidence;


  /*
   * A forward-looking outlook requires
   * a valid Fair Value anchor and usable
   * market evidence.
   *
   * An actionable entry price improves
   * valuation interpretation but is not
   * required to describe the underlying
   * market outlook.
   */
  if (
    input.fairValue === null ||
    input.fairValue <= 0 ||
    confidence === "Insufficient"
  ) {
    return {
      overallOutlook:
        "Unknown",

      overallScore:
        0,

      shortTermOutlook:
        "Unknown",

      shortTermScore:
        0,

      longTermOutlook:
        "Unknown",

      longTermScore:
        0,

      collectorDemand:
        "Unknown",

      collectorDemandScore:
        0,

      supplyOutlook:
        "Unknown",

      supplyScore:
        0,

      marketMaturity:
        "Unknown",

      maturityScore:
        0,

      confidence:
        "Insufficient",

      confidenceScore,

      summary:
        "Additional market data is required before TCGMVP can produce a dependable investment outlook.",

      strengths:
        [],

      headwinds: [
        "Insufficient market evidence limits forward-looking analysis.",
      ],
    };
  }


  const marketRatingScore =
    clamp(
      input.marketRatingScore
    );

  const trendScore =
    clamp(
      input.trendScore
    );

  const riskScore =
    clamp(
      input.riskScore
    );

  const marketHealthScore =
    clamp(
      input.marketHealthScore
    );


  const expectedReturnScore =
    getExpectedReturnScore(
      input.expectedReturnPercent
    );


  const collectorDemandScore =
    calculateCollectorDemandScore(
      input.recentSalesCount,
      input.activeListingsCount
    );


  const supplyScore =
    calculateSupplyScore(
      input.recentSalesCount,
      input.activeListingsCount
    );


  /*
   * Market maturity measures evidence depth
   * and market participation.
   *
   * It is descriptive and does not directly
   * drive the overall outlook.
   */
  const maturityScore =
    roundScore(
      confidenceScore * 0.45 +
      marketHealthScore * 0.25 +
      clamp(
        input.recentSalesCount * 4
      ) * 0.20 +
      clamp(
        input.activeListingsCount * 3
      ) * 0.10
    );


  /*
   * --------------------------------------------------
   * SHORT-TERM OUTLOOK
   * --------------------------------------------------
   *
   * Answers:
   *
   * "What does the next phase of the market
   * look like based on current momentum?"
   *
   * Trend:             45%
   * Expected Return:   30%
   * Market Health:     15%
   * Inverse Risk:      10%
   */
  const shortTermScore =
    roundScore(
      trendScore * 0.45 +
      expectedReturnScore * 0.30 +
      marketHealthScore * 0.15 +
      (100 - riskScore) * 0.10
    );


  /*
   * --------------------------------------------------
   * LONG-TERM OUTLOOK
   * --------------------------------------------------
   *
   * Answers:
   *
   * "Does the underlying market structure
   * support longer-term appreciation?"
   *
   * Market Health:     30%
   * Collector Demand:  25%
   * Supply:            20%
   * Expected Return:   15%
   * Inverse Risk:      10%
   */
  const longTermScore =
    roundScore(
      marketHealthScore * 0.30 +
      collectorDemandScore * 0.25 +
      supplyScore * 0.20 +
      expectedReturnScore * 0.15 +
      (100 - riskScore) * 0.10
    );


  /*
   * --------------------------------------------------
   * OVERALL INVESTMENT OUTLOOK
   * --------------------------------------------------
   *
   * Short Term:        35%
   * Long Term:         45%
   * Market Rating:     20%
   *
   * Market Rating receives only a supporting
   * weight because it already synthesizes several
   * underlying market dimensions.
   *
   * Investment Grade is intentionally excluded
   * to avoid reusing Market Health and valuation
   * evidence yet again.
   */
  let overallScore =
    roundScore(
      shortTermScore * 0.35 +
      longTermScore * 0.45 +
      marketRatingScore * 0.20
    );


  /*
   * Confidence does not make the market bullish
   * or bearish.
   *
   * Instead, lower confidence pulls extreme
   * forward-looking conclusions toward neutral.
   */
  const confidenceMultiplier =
    confidence === "High"
      ? 1
      : confidence === "Medium"
        ? 0.8
        : 0.55;


  overallScore =
    roundScore(
      50 +
      (
        overallScore -
        50
      ) *
      confidenceMultiplier
    );


  const shortTermOutlook =
    getOutlook(
      shortTermScore
    );

  const longTermOutlook =
    getOutlook(
      longTermScore
    );

  const overallOutlook =
    getOutlook(
      overallScore
    );

  const collectorDemand =
    getCollectorDemand(
      collectorDemandScore
    );

  const supplyOutlook =
    getSupplyOutlook(
      supplyScore
    );

  const marketMaturity =
    getMarketMaturity(
      maturityScore
    );


  const strengths: string[] = [];

  const headwinds: string[] = [];


  if (
    trendScore >= 65
  ) {
    strengths.push(
      "Positive market momentum supports the near-term outlook."
    );
  } else if (
    trendScore <= 35
  ) {
    headwinds.push(
      "Weak price momentum creates near-term pressure."
    );
  }


  if (
    marketHealthScore >= 65
  ) {
    strengths.push(
      "Healthy underlying market conditions support the outlook."
    );
  } else if (
    marketHealthScore <= 35
  ) {
    headwinds.push(
      "Weak market health reduces long-term conviction."
    );
  }


  if (
    collectorDemandScore >= 65
  ) {
    strengths.push(
      "Strong observed buyer activity supports collector demand."
    );
  } else if (
    collectorDemandScore <= 35
  ) {
    headwinds.push(
      "Limited observed buyer activity weakens demand support."
    );
  }


  if (
    riskScore <= 35
  ) {
    strengths.push(
      "Lower overall risk supports a more dependable outlook."
    );
  } else if (
    riskScore >= 65
  ) {
    headwinds.push(
      "Elevated risk may produce greater price instability."
    );
  }


  if (
    supplyScore >= 65
  ) {
    strengths.push(
      "Strong inventory absorption suggests relatively constrained supply."
    );
  } else if (
    supplyScore <= 35
  ) {
    headwinds.push(
      "Available supply appears high relative to recent sales activity."
    );
  }


  if (
    input.expectedReturnPercent !==
      null &&
    input.expectedReturnPercent >=
      8
  ) {
    strengths.push(
      "The current price target indicates meaningful potential return from the best available entry price."
    );
  } else if (
    input.expectedReturnPercent !==
      null &&
    input.expectedReturnPercent <
      0
  ) {
    headwinds.push(
      "The current price target indicates limited near-term upside from the best available entry price."
    );
  }


  /*
   * Entry valuation must use the actionable
   * listing price rather than reference price.
   */
  if (
    input.entryPrice !== null &&
    input.entryPrice > 0
  ) {
    if (
      input.entryPrice >
      input.fairValue * 1.03
    ) {
      headwinds.push(
        "The best available entry price is above estimated fair value."
      );
    } else if (
      input.entryPrice <
      input.fairValue * 0.9
    ) {
      strengths.push(
        "The best available entry price provides a meaningful valuation cushion."
      );
    }
  } else {
    headwinds.push(
      "An actionable entry price is unavailable, limiting valuation analysis."
    );
  }


  if (
    confidence === "Low"
  ) {
    headwinds.push(
      "Limited market evidence reduces outlook confidence."
    );
  }


  const summary =
    buildSummary({
      overallOutlook,

      shortTermOutlook,

      longTermOutlook,

      collectorDemand,

      supplyOutlook,

      expectedReturnPercent:
        input.expectedReturnPercent,

      entryPrice:
        input.entryPrice,

      fairValue:
        input.fairValue,
    });


  return {
    overallOutlook,

    overallScore,

    shortTermOutlook,

    shortTermScore,

    longTermOutlook,

    longTermScore,

    collectorDemand,

    collectorDemandScore,

    supplyOutlook,

    supplyScore,

    marketMaturity,

    maturityScore,

    confidence,

    confidenceScore,

    summary,

    strengths:
      strengths.slice(
        0,
        5
      ),

    headwinds:
      headwinds.slice(
        0,
        5
      ),
  };
}